name: Azure Static Web Apps CI/CD - React Frontend

on:
  push:
    branches:
      - main
      - frontend-refactor
    paths:
      - 'filmrecommendations-react-frontend/**'
      - '.github/workflows/azure-static-web-apps-react-frontend.yml'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - 'filmrecommendations-react-frontend/**'
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_REACT_FRONTEND }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations ######
          app_location: "filmrecommendations-react-frontend" # App source code path (no leading slash)
          api_location: "" # Api source code path - optional
          output_location: "dist" # Built app content directory (Vite's default output folder)
          ###### End of Repository/Build Configurations ######
        env:
          # Environment variables for the build
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_REACT_FRONTEND }}
          action: "close"
          app_location: "filmrecommendations-react-frontend"
