name: Build and Deploy API
on:
  push:
    branches: [ "master" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup .NET 9.0 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore NuGet packages
        run: dotnet restore ./FilmRecomendations.WebApi/FilmRecomendations.WebApi.csproj

      - name: Build API
        run: dotnet build --configuration Release ./FilmRecomendations.WebApi/FilmRecomendations.WebApi.csproj

      - name: Run EF database migrations
        run: |
          dotnet tool install --global dotnet-ef
          cd ./FilmRecomendations.WebApi
          dotnet ef database update
        env:
          ConnectionStrings__FilmConnectionString: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}

      - name: Publish API for deployment
        run: dotnet publish --configuration Release --output publish
        working-directory: ./FilmRecomendations.WebApi

      - name: Deploy to Azure App Service (Backend API)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ai-film-recommendations
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_API }}
          package: ./FilmRecomendations.WebApi/publish
